export default {
  GENERIC: {
    INTERNAL: 'ERR_SERVER_INTERNAL_ERROR',
    UNAUTHORIZED: 'ERR_UNAUTHORIZED',
    FORBIDDEN: 'ERR_FORBIDDEN',
    NOT_FOUND: 'ERR_NOT_FOUND',
  },
  FORM: {
    MISSING_FIELDS: 'ERR_MISSING_FIELDS',
  },
  AUTH: {
    INVALID_TOKEN: 'ERR_INVALID_TOKEN',
    EXPIRED_TOKEN: 'ERR_EXPIRED_TOKEN',
    INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
    REGISTERED: 'SUCCESSFULLY_REGISTERED',
    LOGGED_IN: 'SUCCESSFULLY_LOGGED_IN',
    LOGGED_OUT: 'SUCCESSFULLY_LOGGED_OUT',
  },
};
